name-template: '🚀 v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💡 Features'
    labels:
      - '🌈 Feature'
  - title: '🐛 Bug fixes'
    labels:
      - '⚠️ Bug'
  - title: '🤯 Inner Changes'
    labels:
      - '📦 Chore'
      - '📃 Docs'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## 🚀 What has changed in this version?
  ---
  $CHANGES
no-changes-template: 'No changes.'